language: node_js
dist: trusty
node_js:
  - 6
  - 8
notifications:
  email:
    on_failure: change
script:
  - node --version
  - yarn --version
  - yarn run lint && yarn run test
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules